version: '3.9'
services:
  blockchain:
    container_name: blockchain
    build:
      context: .
      dockerfile: ./BlockChain/Dockerfile
    ports:
      - "8081:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  coordinador:
    container_name: coordinador
    build:
      context: .
      dockerfile: ./Coordinador/Dockerfile
    ports:
      - "8082:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    
  validador:
    container_name: validador
    build:
      context: .
      dockerfile: ./Validador/Dockerfile
    ports:
      - "8083:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  cerrarbloque:
    container_name: cerrarbloque
    build:
      context: .
      dockerfile: ./CerrarBloque/Dockerfile
    ports:
      - "8084:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
